"""Fix Role.permissions to ARRAY(String)

Revision ID: 342f82f975c9
Revises: 54126cb52b08
Create Date: 2025-11-30 23:54:59.082052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342f82f975c9'
down_revision: Union[str, None] = '54126cb52b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
                    existing_type=sa.JSON(),
                    type_=postgresql.ARRAY(sa.String()),
                    postgresql_using="permissions::text[]",
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'images',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('payment', 'provider_data',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###
