"""Add is_admin field to User model

Revision ID: 54126cb52b08
Revises: 6334c82f2677
Create Date: 2025-11-30 23:41:05.802754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54126cb52b08'
down_revision: Union[str, None] = '6334c82f2677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('role', 'permissions',
                    existing_type=sa.JSON(),
                    type_=postgresql.ARRAY(sa.VARCHAR()),
                    existing_nullable=True)
    op.alter_column('product', 'images',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('payment', 'provider_data',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###
